### ISSUE TITLE
Water leak sensor

### ISSUE THREAD

**Issue by zmechu** [CestLaGalere/mobilealerts#5]
Hello!
I have got Mobile Alerts sensor:
https://mobile-alerts.eu/en/temperatur-und-luftfeuchtesensor-mit-zusaetzlichem-wasserdetektor-ma-10350-2/
It has ability to measure temperature, humidity and has water leak sensor.

Under HA it returns attributes:

![ma](https://github.com/CestLaGalere/mobilealerts/assets/38977032/f8bd1552-92ff-4e72-a2a7-a73c50b9142e)

Measuring temperature and humidity works fine. My question is: how to get information from water leak sensor?
Thank you in advance!

**Comment by petrleocompel** [comment]
Can you test what value will change if you "trigger" the leak sensor ?

Please post measurements before and after triggering to clearly see what we should look on. 

Then we will add it to the entities for support (it will have to be configured)

**Comment by zmechu** [comment]
Hello! 
Sorry for delay!
Seems to be clear. Water sensor not triggered:
![obraz](https://github.com/CestLaGalere/mobilealerts/assets/38977032/fc19ca04-f871-4f34-83ca-c03943ba7293)
Triggered:
![obraz](https://github.com/CestLaGalere/mobilealerts/assets/38977032/207f3872-e610-48e6-895b-9f5d47811378)
Then not triggered:
![obraz](https://github.com/CestLaGalere/mobilealerts/assets/38977032/2a9451fc-664b-44eb-9717-5e2d0c328e52)
So, "t2" attribute shows water sensor. Voila :-)

Only one thing: "t2" attribute shows temperature, and water leak sensor is decoded as "0,0 °C" or "1,0 °C" when triggered. It can be "fixed" using templates, but maybe there is more convenient way?

**Comment by petrleocompel** [comment]
@zmechu can you post your configuration for mobilealerts ? 
Delete account related info. This sensor is needed.

I guess we should introduce new type for water leak sensor and correctly decode it. I will take look in docs for it, what will be the best implementation.

**Comment by CestLaGalere** [comment]
@zmechu do you have curl?  if so please try the command below (replace XXXXXXXX with your deviceid & post the json response here. if you cannot run this I am happy to do so if I can have your deviceid - it will allow me to see what data is returned.  Thanks.  Their documentation is outdated as it does not show any info on water leak sensors.

curl -d "{'deviceids': 'XXXXXXXXX'}" -H "Content-Type: application/json" https://www.data199.com/api/pv1/device/lastmeasurement

**Comment by zmechu** [comment]
```
curl -d "{'deviceids': 'XXXXXXXXX'}" -H "Content-Type: application/json" https://www.data199.com/api/pv1/device/lastmeasurement
{
  "devices": [
    {
      "deviceid": "XXXXXXXXX",
      "lastseen": 1690390222,
      "lowbattery": false,
      "measurement": {
        "idx": 143389,
        "ts": 1690390217,
        "c": 1690390222,
        "lb": false,
        "t1": 23.0,
        "t2": 0.0,
        "h": 48.0
      }
    }
  ],
  "success": true
```

**Comment by CestLaGalere** [comment]
I have created a Water sensor that needs the setup:
```
      - device_id: YYYYYYYYY
        name: WATER YYYYYYYYY
        type: water
```
this should return two states: 'dry' and 'wet' (to correspond to the Mobile Alerts app UI.

**Comment by zmechu** [comment]
Almost perfect :-)
mobile_alerts updated, HA restarted, and errors in log:
```
Logger: homeassistant.components.sensor
Source: custom_components/mobile_alerts/sensor.py:312
Integration: Sensor (documentation, issues)
First occurred: 19:16:08 (2 occurrences)
Last logged: 19:16:09

Error adding entities for domain sensor with platform mobile_alerts
Error while setting up mobile_alerts platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 478, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mobile_alerts/sensor.py", line 312, in native_value
    return WATER_SENSOR_WET
           ^^^^^^^^^^^^^^^^
NameError: name 'WATER_SENSOR_WET' is not defined
```

**Comment by CestLaGalere** [comment]
@zmechu apologies - missed this & didn't look at the logs!

**Comment by zmechu** [comment]
99% done :-) Kind of data types conversion...

```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:594
Integration: Sensor (documentation, issues)
First occurred: 22:38:28 (2 occurrences)
Last logged: 22:38:28

Error adding entities for domain sensor with platform mobile_alerts
Error while setting up mobile_alerts platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 592, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'wet'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 594, in state
    raise ValueError(
ValueError: Sensor sensor.water_xxxxx has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'wet' (<class 'str'>)
```

**Comment by CestLaGalere** [comment]
@petrleocompel any ideas?  the SensorDeviceClass doesn't have a sensor that returns a string unfortunately - do we need to add a sensor that can do this, then revisit this sensor when this is available? I don't have the time as a beginner to get up to speed with the internal workings as to how to get this sorted.  Thanks

**Comment by petrleocompel** [comment]
I will check today evening the best way.

**Comment by petrleocompel** [comment]
Correct integration of "flood sensor / Leak sensor" should be -> `BinarySensorDeviceClass.MOISTURE`

I will step in and fix it.

**Comment by CestLaGalere** [comment]
Thanks for the pointer - I have made the change but not committed it yet - 
I am assuming we need:
```
class MobileAlertsWaterSensor(MobileAlertsSensor, CoordinatorEntity, SensorEntity):
    """Implementation of a MobileAlerts humidity sensor. """

    def __init__(self, coordinator, device: dict[str, str]) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator, device=device)
        self._device_class = None
        self._attr_native_unit_of_measurement = None
        self._type = "t2"
        self.entity_description = BinarySensorEntityDescription(
            BinarySensorDeviceClass.MOISTURE,
            device_class=BinarySensorDeviceClass.MOISTURE,
            state_class=SensorStateClass.MEASUREMENT,
            native_unit_of_measurement=None,
        )

    @property
    def native_value(self) -> StateType:
        if self._attr_native_value == 0:
            return STATE_OFF
        else:
            return STATE_ON
```

**Comment by CestLaGalere** [comment]
@zmechu try that.
Chris

**Comment by zmechu** [comment]
Still errors....
```
Logger: homeassistant.components.sensor
Source: custom_components/mobile_alerts/sensor.py:303
Integration: Sensor (documentation, issues)
First occurred: 10:52:34 (1 occurrences)
Last logged: 10:52:34

Error while setting up mobile_alerts platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mobile_alerts/sensor.py", line 130, in async_setup_platform
    sensors.append(MobileAlertsWaterSensor(coordinator, device))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mobile_alerts/sensor.py", line 303, in __init__
    self.entity_description = BinarySensorEntityDescription(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BinarySensorEntityDescription.__init__() got an unexpected keyword argument 'state_class'
```

**Comment by petrleocompel** [comment]
For these test builds @CestLaGalere  we should make "beta" releases. 
And have stable release for normal.

Example here  https://github.com/petrleocompel/hikaxpro_hacs/releases
![Screenshot 2023-07-31 at 6 57 48](https://github.com/CestLaGalere/mobilealerts/assets/9423543/8a174b5e-a773-464c-910a-49d81ede59e6)

You can release as many versions you want. Just keep the suffix for the beta release in this format. And people who do not need it will stay on stable version.

**Comment by CestLaGalere** [comment]
@petrleocompel - I'm going round in circles here - I implemented this as below, it generates an error but I cannot see where it needs fixing!
```
class MobileAlertsWaterSensor(MobileAlertsSensor, CoordinatorEntity, BinarySensorEntity):
    """Implementation of a MobileAlerts humidity sensor. """

    def __init__(self, coordinator, device: dict[str, str]) -> None:
        """Initialize the sensor."""
        super().__init__(coordinator, device=device)
        self._device_class = None
        self._attr_native_unit_of_measurement = None
        self._type = "t2"
        self.entity_description = BinarySensorEntityDescription(
            BinarySensorDeviceClass.MOISTURE,
            device_class=SensorDeviceClass.MOISTURE,
        )

    @property
    def native_value(self) -> StateType:
        if self._attr_native_value == 0:
            return STATE_OFF
        else:
            return STATE_ON
```

It generates the error below, to me it seems hass requires a unit of measurement, however the binary sensor doesn't seem to provide one. 

```
2023-08-03 18:37:26.709 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform mobile_alerts
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 566, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 208, in add_to_platform_start
    self._sensor_option_unit_of_measurement = self._get_initial_suggested_unit()
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 337, in _get_initial_suggested_unit
    suggested_unit_of_measurement = self.suggested_unit_of_measurement
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 441, in suggested_unit_of_measurement
    return self.entity_description.suggested_unit_of_measurement
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BinarySensorEntityDescription' object has no attribute 'suggested_unit_of_measurement'
```

**Comment by petrleocompel** [comment]
Any details for testing ?

**Comment by CestLaGalere** [comment]
no, I added it to an existing temperature sensor ID so that it would get created and I could check the creation (it would then fail to get a value but that't the next step!)

**Comment by petrleocompel** [comment]
I see the problem the `MobileAlertsSensor` is extending `SensorEntity`. I will try to provide fix.

**Comment by petrleocompel** [comment]
@CestLaGalere @zmechu please try now

**Comment by zmechu** [comment]
Errors... All sensora are down now. Maybe lets test it with kind of "beta" channel?
```
Logger: homeassistant.components.sensor
Source: custom_components/mobile_alerts/sensor.py:301
Integration: Sensor (documentation, issues)
First occurred: 21:39:04 (1 occurrences)
Last logged: 21:39:04

Error while setting up mobile_alerts platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mobile_alerts/sensor.py", line 132, in async_setup_platform
    sensors.append(MobileAlertsWaterSensor(coordinator, device))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mobile_alerts/sensor.py", line 301, in __init__
    super().__init__(coordinator, device=device)
TypeError: CoordinatorEntity.__init__() got an unexpected keyword argument 'device'
```

**Comment by petrleocompel** [comment]
Quick fix for you @zmechu landed with last provided feedback. 
Yes I agree. Next version will be released as version 1.0.0. And later these tests will land as separate versions.

**Comment by CestLaGalere** [comment]
@petrleocompel thanks - seems odd that we cannot extend the MobileAlertsSensor - the BinarySensor should provide stubs for unit_of_measurement etc? Or do we need another base class to provide the extract_reading & _handle_coordinator_update for all MobileAlertsXXXXXSensor classes?

**Comment by petrleocompel** [comment]
@CestLaGalere 
Well the `BinarySensor` is not "normal `Sensor`"
Later i might create `MobileAlertsBinarySensor` but right now it is single entity.

We could have `MobileAlertsSensor` extend just `Entity`.
But the handling is different for `Sensor` and `BinarySensor` soooo it does not make sense.

Later having `MobileAlertsBinarySensor` seems like only option but currently not needed. 
Should be fixed. After @zmechu  will test we can release it as normal version.

**Comment by petrleocompel** [comment]
@zmechu any update ? can you check the latest "released version" `1.2.0-beta1` ?

**Comment by zmechu** [comment]
> @zmechu any update ? can you check the latest "released version" `1.2.0-beta1` ?

Still the same. There is no errors in HA log, but leak sensors has "unknown" state.
![obraz](https://github.com/CestLaGalere/mobilealerts/assets/38977032/f62ba5c1-4bd7-4bd6-9c60-a1f055bd93e5)

**Comment by petrleocompel** [comment]
> "devices": [
>     {
>       "deviceid": "XXXXXXXXX",
>       "lastseen": 1690390222,
>       "lowbattery": false,
>       "measurement": {
>         "idx": 143389,
>         "ts": 1690390217,
>         "c": 1690390222,
>         "lb": false,
>         "t1": 23.0,
>         "t2": 0.0,
>         "h": 48.0
>       }
>     }

Found the API. I will take a look on this today
